name: Page
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '33 3 * * 1'

jobs:
  build:
    name: Build and publish page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build static files
        run: |
          git clone https://github.com/glowing-bear/glowing-bear.git
          cd glowing-bear
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: glowing-bear/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
